### ISSUE TITLE
Bug: Input UX on settings page

### ISSUE THREAD

**Issue by ai-slave** [Major-Eth/yUITemplate#63]
### What happened 🆘
Save button is out of sight and is very hard to notice. Clicking “Enter” doesn’t save the value too so first time I was under impresion that the feature isn’t working. 

### To Reproduce 🔂
1. go to /settings/
2. change any input

### More 🔎
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/6696080/202928781-c9555365-2c4d-4947-8e8f-9834fada773c.png">

**Comment by ai-slave** [comment]
It's happening because primary color isn't specified. I can just change it to "neutral" which is declared and it'll be better than what it is now, or just need some guidance from someone who understands the codebase better. 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/6696080/202929221-4339c6fb-66ea-4abd-84f8-5b673694251c.png">

**Comment by Majorfi** [comment]
This page should be reworked to match the style in https://y.finance/about (for example)!

**Comment by 0xBasically** [comment]
@Majorfi this is a pretty old issue still relevant?
